<?php

namespace Proxies\__CG__\proyectos\hojaVidaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CalJudFis extends \proyectos\hojaVidaBundle\Entity\CalJudFis implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPkExpJudFis()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["pkExpJudFis"];
        }
        $this->__load();
        return parent::getPkExpJudFis();
    }

    public function setNumExp($numExp)
    {
        $this->__load();
        return parent::setNumExp($numExp);
    }

    public function getNumExp()
    {
        $this->__load();
        return parent::getNumExp();
    }

    public function setTipResolucion($tipResolucion)
    {
        $this->__load();
        return parent::setTipResolucion($tipResolucion);
    }

    public function getTipResolucion()
    {
        $this->__load();
        return parent::getTipResolucion();
    }

    public function setFechaRes($fechaRes)
    {
        $this->__load();
        return parent::setFechaRes($fechaRes);
    }

    public function getFechaRes()
    {
        $this->__load();
        return parent::getFechaRes();
    }

    public function setDdagraviado($ddagraviado)
    {
        $this->__load();
        return parent::setDdagraviado($ddagraviado);
    }

    public function getDdagraviado()
    {
        $this->__load();
        return parent::getDdagraviado();
    }

    public function setDdagresor($ddagresor)
    {
        $this->__load();
        return parent::setDdagresor($ddagresor);
    }

    public function getDdagresor()
    {
        $this->__load();
        return parent::getDdagresor();
    }

    public function setMateria($materia)
    {
        $this->__load();
        return parent::setMateria($materia);
    }

    public function getMateria()
    {
        $this->__load();
        return parent::getMateria();
    }

    public function setEspecialidad($especialidad)
    {
        $this->__load();
        return parent::setEspecialidad($especialidad);
    }

    public function getEspecialidad()
    {
        $this->__load();
        return parent::getEspecialidad();
    }

    public function setNota($nota)
    {
        $this->__load();
        return parent::setNota($nota);
    }

    public function getNota()
    {
        $this->__load();
        return parent::getNota();
    }

    public function setPkExpProfesional($pkExpProfesional)
    {
        $this->__load();
        return parent::setPkExpProfesional($pkExpProfesional);
    }

    public function getPkExpProfesional()
    {
        $this->__load();
        return parent::getPkExpProfesional();
    }

    public function setUsuarioAudt($usuarioAudt)
    {
        $this->__load();
        return parent::setUsuarioAudt($usuarioAudt);
    }

    public function getUsuarioAudt()
    {
        $this->__load();
        return parent::getUsuarioAudt();
    }

    public function setFechaAudt($fechaAudt)
    {
        $this->__load();
        return parent::setFechaAudt($fechaAudt);
    }

    public function getFechaAudt()
    {
        $this->__load();
        return parent::getFechaAudt();
    }

    public function setIpAudt($ipAudt)
    {
        $this->__load();
        return parent::setIpAudt($ipAudt);
    }

    public function getIpAudt()
    {
        $this->__load();
        return parent::getIpAudt();
    }

    public function setEstadoAudt($estadoAudt)
    {
        $this->__load();
        return parent::setEstadoAudt($estadoAudt);
    }

    public function getEstadoAudt()
    {
        $this->__load();
        return parent::getEstadoAudt();
    }

    public function setPkDatPostulante(\proyectos\hojaVidaBundle\Entity\DatosPostulante $pkDatPostulante = NULL)
    {
        $this->__load();
        return parent::setPkDatPostulante($pkDatPostulante);
    }

    public function getPkDatPostulante()
    {
        $this->__load();
        return parent::getPkDatPostulante();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pkExpJudFis', 'numExp', 'tipResolucion', 'fechaRes', 'ddagraviado', 'ddagresor', 'materia', 'especialidad', 'nota', 'pkExpProfesional', 'usuarioAudt', 'fechaAudt', 'ipAudt', 'estadoAudt', 'pkDatPostulante');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}