<?php

namespace Proxies\__CG__\proyectos\curriculoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TrTipoCargo extends \proyectos\curriculoBundle\Entity\TrTipoCargo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdTipoCargo()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idTipoCargo"];
        }
        $this->__load();
        return parent::getIdTipoCargo();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setIdConvocatoria(\proyectos\curriculoBundle\Entity\TmConvocatoria $idConvocatoria = NULL)
    {
        $this->__load();
        return parent::setIdConvocatoria($idConvocatoria);
    }

    public function getIdConvocatoria()
    {
        $this->__load();
        return parent::getIdConvocatoria();
    }

    public function setIdPlaza(\proyectos\curriculoBundle\Entity\TrPlaza $idPlaza = NULL)
    {
        $this->__load();
        return parent::setIdPlaza($idPlaza);
    }

    public function getIdPlaza()
    {
        $this->__load();
        return parent::getIdPlaza();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idTipoCargo', 'descripcion', 'idConvocatoria', 'idPlaza');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}