<?php

namespace Proxies\__CG__\proyectos\hojaVidaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DatosPostulante extends \proyectos\hojaVidaBundle\Entity\DatosPostulante implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPkDatPostulante()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["pkDatPostulante"];
        }
        $this->__load();
        return parent::getPkDatPostulante();
    }

    public function setPkSusuario($pkSusuario)
    {
        $this->__load();
        return parent::setPkSusuario($pkSusuario);
    }

    public function getPkSusuario()
    {
        $this->__load();
        return parent::getPkSusuario();
    }

    public function setCargoAPostular($cargoAPostular)
    {
        $this->__load();
        return parent::setCargoAPostular($cargoAPostular);
    }

    public function getCargoAPostular()
    {
        $this->__load();
        return parent::getCargoAPostular();
    }

    public function setCondicion($condicion)
    {
        $this->__load();
        return parent::setCondicion($condicion);
    }

    public function getCondicion()
    {
        $this->__load();
        return parent::getCondicion();
    }

    public function setTipoCurso($tipoCurso)
    {
        $this->__load();
        return parent::setTipoCurso($tipoCurso);
    }

    public function getTipoCurso()
    {
        $this->__load();
        return parent::getTipoCurso();
    }

    public function setNota($nota)
    {
        $this->__load();
        return parent::setNota($nota);
    }

    public function getNota()
    {
        $this->__load();
        return parent::getNota();
    }

    public function setPrePromedio($prePromedio)
    {
        $this->__load();
        return parent::setPrePromedio($prePromedio);
    }

    public function getPrePromedio()
    {
        $this->__load();
        return parent::getPrePromedio();
    }

    public function setOrdenMerito($ordenMerito)
    {
        $this->__load();
        return parent::setOrdenMerito($ordenMerito);
    }

    public function getOrdenMerito()
    {
        $this->__load();
        return parent::getOrdenMerito();
    }

    public function setPlazasVacantes($plazasVacantes)
    {
        $this->__load();
        return parent::setPlazasVacantes($plazasVacantes);
    }

    public function getPlazasVacantes()
    {
        $this->__load();
        return parent::getPlazasVacantes();
    }

    public function setExamenConocimientos($examenConocimientos)
    {
        $this->__load();
        return parent::setExamenConocimientos($examenConocimientos);
    }

    public function getExamenConocimientos()
    {
        $this->__load();
        return parent::getExamenConocimientos();
    }

    public function setAfiliacionCurricular($afiliacionCurricular)
    {
        $this->__load();
        return parent::setAfiliacionCurricular($afiliacionCurricular);
    }

    public function getAfiliacionCurricular()
    {
        $this->__load();
        return parent::getAfiliacionCurricular();
    }

    public function setUsuarioAudt($usuarioAudt)
    {
        $this->__load();
        return parent::setUsuarioAudt($usuarioAudt);
    }

    public function getUsuarioAudt()
    {
        $this->__load();
        return parent::getUsuarioAudt();
    }

    public function setFechaAudt($fechaAudt)
    {
        $this->__load();
        return parent::setFechaAudt($fechaAudt);
    }

    public function getFechaAudt()
    {
        $this->__load();
        return parent::getFechaAudt();
    }

    public function setIpAudt($ipAudt)
    {
        $this->__load();
        return parent::setIpAudt($ipAudt);
    }

    public function getIpAudt()
    {
        $this->__load();
        return parent::getIpAudt();
    }

    public function setEstadoAudt($estadoAudt)
    {
        $this->__load();
        return parent::setEstadoAudt($estadoAudt);
    }

    public function getEstadoAudt()
    {
        $this->__load();
        return parent::getEstadoAudt();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pkDatPostulante', 'pkSusuario', 'cargoAPostular', 'condicion', 'tipoCurso', 'nota', 'prePromedio', 'ordenMerito', 'plazasVacantes', 'examenConocimientos', 'afiliacionCurricular', 'usuarioAudt', 'fechaAudt', 'ipAudt', 'estadoAudt');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}