<?php

namespace Proxies\__CG__\proyectos\curriculoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TmCurriculo extends \proyectos\curriculoBundle\Entity\TmCurriculo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdCurriculo()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idCurriculo"];
        }
        $this->__load();
        return parent::getIdCurriculo();
    }

    public function setFechaAuditoria($fechaAuditoria)
    {
        $this->__load();
        return parent::setFechaAuditoria($fechaAuditoria);
    }

    public function getFechaAuditoria()
    {
        $this->__load();
        return parent::getFechaAuditoria();
    }

    public function setFlagCompleto($flagCompleto)
    {
        $this->__load();
        return parent::setFlagCompleto($flagCompleto);
    }

    public function getFlagCompleto()
    {
        $this->__load();
        return parent::getFlagCompleto();
    }

    public function setEstadoEvaluador1($estadoEvaluador1)
    {
        $this->__load();
        return parent::setEstadoEvaluador1($estadoEvaluador1);
    }

    public function getEstadoEvaluador1()
    {
        $this->__load();
        return parent::getEstadoEvaluador1();
    }

    public function setEstadoEvaluador2($estadoEvaluador2)
    {
        $this->__load();
        return parent::setEstadoEvaluador2($estadoEvaluador2);
    }

    public function getEstadoEvaluador2()
    {
        $this->__load();
        return parent::getEstadoEvaluador2();
    }

    public function setEstadoEvaluado($estadoEvaluado)
    {
        $this->__load();
        return parent::setEstadoEvaluado($estadoEvaluado);
    }

    public function getEstadoEvaluado()
    {
        $this->__load();
        return parent::getEstadoEvaluado();
    }

    public function addDni(\proyectos\curriculoBundle\Entity\SUsuario $dni)
    {
        $this->__load();
        return parent::addDni($dni);
    }

    public function removeDni(\proyectos\curriculoBundle\Entity\SUsuario $dni)
    {
        $this->__load();
        return parent::removeDni($dni);
    }

    public function getDni()
    {
        $this->__load();
        return parent::getDni();
    }

    public function setIdTipoCargo(\proyectos\curriculoBundle\Entity\TrTipoCargo $idTipoCargo = NULL)
    {
        $this->__load();
        return parent::setIdTipoCargo($idTipoCargo);
    }

    public function getIdTipoCargo()
    {
        $this->__load();
        return parent::getIdTipoCargo();
    }

    public function setIdPlaza(\proyectos\curriculoBundle\Entity\TrPlaza $idPlaza = NULL)
    {
        $this->__load();
        return parent::setIdPlaza($idPlaza);
    }

    public function getIdPlaza()
    {
        $this->__load();
        return parent::getIdPlaza();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idCurriculo', 'fechaAuditoria', 'flagCompleto', 'estadoEvaluador1', 'estadoEvaluador2', 'estadoEvaluado', 'dni', 'idTipoCargo', 'idPlaza');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}