<?php

namespace Proxies\__CG__\proyectos\hojaVidaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Publicaciones extends \proyectos\hojaVidaBundle\Entity\Publicaciones implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPkPublicaciones()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["pkPublicaciones"];
        }
        $this->__load();
        return parent::getPkPublicaciones();
    }

    public function setLibrosTextosUniv($librosTextosUniv)
    {
        $this->__load();
        return parent::setLibrosTextosUniv($librosTextosUniv);
    }

    public function getLibrosTextosUniv()
    {
        $this->__load();
        return parent::getLibrosTextosUniv();
    }

    public function setInvJuridicas($invJuridicas)
    {
        $this->__load();
        return parent::setInvJuridicas($invJuridicas);
    }

    public function getInvJuridicas()
    {
        $this->__load();
        return parent::getInvJuridicas();
    }

    public function setEnsayosJuridico($ensayosJuridico)
    {
        $this->__load();
        return parent::setEnsayosJuridico($ensayosJuridico);
    }

    public function getEnsayosJuridico()
    {
        $this->__load();
        return parent::getEnsayosJuridico();
    }

    public function setArticulosJuridicos($articulosJuridicos)
    {
        $this->__load();
        return parent::setArticulosJuridicos($articulosJuridicos);
    }

    public function getArticulosJuridicos()
    {
        $this->__load();
        return parent::getArticulosJuridicos();
    }

    public function setArticulosNoJuridicos($articulosNoJuridicos)
    {
        $this->__load();
        return parent::setArticulosNoJuridicos($articulosNoJuridicos);
    }

    public function getArticulosNoJuridicos()
    {
        $this->__load();
        return parent::getArticulosNoJuridicos();
    }

    public function setUsuarioAudt($usuarioAudt)
    {
        $this->__load();
        return parent::setUsuarioAudt($usuarioAudt);
    }

    public function getUsuarioAudt()
    {
        $this->__load();
        return parent::getUsuarioAudt();
    }

    public function setFechaAudt($fechaAudt)
    {
        $this->__load();
        return parent::setFechaAudt($fechaAudt);
    }

    public function getFechaAudt()
    {
        $this->__load();
        return parent::getFechaAudt();
    }

    public function setIpAudt($ipAudt)
    {
        $this->__load();
        return parent::setIpAudt($ipAudt);
    }

    public function getIpAudt()
    {
        $this->__load();
        return parent::getIpAudt();
    }

    public function setEstadoAudt($estadoAudt)
    {
        $this->__load();
        return parent::setEstadoAudt($estadoAudt);
    }

    public function getEstadoAudt()
    {
        $this->__load();
        return parent::getEstadoAudt();
    }

    public function setPkDatPostulante(\proyectos\hojaVidaBundle\Entity\DatosPostulante $pkDatPostulante = NULL)
    {
        $this->__load();
        return parent::setPkDatPostulante($pkDatPostulante);
    }

    public function getPkDatPostulante()
    {
        $this->__load();
        return parent::getPkDatPostulante();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pkPublicaciones', 'librosTextosUniv', 'invJuridicas', 'ensayosJuridico', 'articulosJuridicos', 'articulosNoJuridicos', 'usuarioAudt', 'fechaAudt', 'ipAudt', 'estadoAudt', 'pkDatPostulante');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}