<?php

namespace Proxies\__CG__\proyectos\curriculoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TdCurriculoCampo extends \proyectos\curriculoBundle\Entity\TdCurriculoCampo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setFechaAuditoria($fechaAuditoria)
    {
        $this->__load();
        return parent::setFechaAuditoria($fechaAuditoria);
    }

    public function getFechaAuditoria()
    {
        $this->__load();
        return parent::getFechaAuditoria();
    }

    public function setFechaAnulacion($fechaAnulacion)
    {
        $this->__load();
        return parent::setFechaAnulacion($fechaAnulacion);
    }

    public function getFechaAnulacion()
    {
        $this->__load();
        return parent::getFechaAnulacion();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setIdCampo(\proyectos\curriculoBundle\Entity\TdCampos $idCampo = NULL)
    {
        $this->__load();
        return parent::setIdCampo($idCampo);
    }

    public function getIdCampo()
    {
        $this->__load();
        return parent::getIdCampo();
    }

    public function setIdCurriculoItem(\proyectos\curriculoBundle\Entity\TdCurriculoItem $idCurriculoItem = NULL)
    {
        $this->__load();
        return parent::setIdCurriculoItem($idCurriculoItem);
    }

    public function getIdCurriculoItem()
    {
        $this->__load();
        return parent::getIdCurriculoItem();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'descripcion', 'fechaAuditoria', 'fechaAnulacion', 'estado', 'idCampo', 'idCurriculoItem');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}