<?php

namespace Proxies\__CG__\proyectos\hojaVidaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class InformacionPatrimonialConyuge extends \proyectos\hojaVidaBundle\Entity\InformacionPatrimonialConyuge implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPkInformacionPatCon()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["pkInformacionPatCon"];
        }
        $this->__load();
        return parent::getPkInformacionPatCon();
    }

    public function setAnoEje($anoEje)
    {
        $this->__load();
        return parent::setAnoEje($anoEje);
    }

    public function getAnoEje()
    {
        $this->__load();
        return parent::getAnoEje();
    }

    public function setIngresoAnualPublico($ingresoAnualPublico)
    {
        $this->__load();
        return parent::setIngresoAnualPublico($ingresoAnualPublico);
    }

    public function getIngresoAnualPublico()
    {
        $this->__load();
        return parent::getIngresoAnualPublico();
    }

    public function setIngresoAnualPrivado($ingresoAnualPrivado)
    {
        $this->__load();
        return parent::setIngresoAnualPrivado($ingresoAnualPrivado);
    }

    public function getIngresoAnualPrivado()
    {
        $this->__load();
        return parent::getIngresoAnualPrivado();
    }

    public function setTotalIngresoAnualPromedio($totalIngresoAnualPromedio)
    {
        $this->__load();
        return parent::setTotalIngresoAnualPromedio($totalIngresoAnualPromedio);
    }

    public function getTotalIngresoAnualPromedio()
    {
        $this->__load();
        return parent::getTotalIngresoAnualPromedio();
    }

    public function setAhorrosSistema($ahorrosSistema)
    {
        $this->__load();
        return parent::setAhorrosSistema($ahorrosSistema);
    }

    public function getAhorrosSistema()
    {
        $this->__load();
        return parent::getAhorrosSistema();
    }

    public function setAhorrosSinCustodia($ahorrosSinCustodia)
    {
        $this->__load();
        return parent::setAhorrosSinCustodia($ahorrosSinCustodia);
    }

    public function getAhorrosSinCustodia()
    {
        $this->__load();
        return parent::getAhorrosSinCustodia();
    }

    public function setNroPersonas($nroPersonas)
    {
        $this->__load();
        return parent::setNroPersonas($nroPersonas);
    }

    public function getNroPersonas()
    {
        $this->__load();
        return parent::getNroPersonas();
    }

    public function setAcreencias($acreencias)
    {
        $this->__load();
        return parent::setAcreencias($acreencias);
    }

    public function getAcreencias()
    {
        $this->__load();
        return parent::getAcreencias();
    }

    public function setIngresoAnualConyuge($ingresoAnualConyuge)
    {
        $this->__load();
        return parent::setIngresoAnualConyuge($ingresoAnualConyuge);
    }

    public function getIngresoAnualConyuge()
    {
        $this->__load();
        return parent::getIngresoAnualConyuge();
    }

    public function setUsuarioAudt($usuarioAudt)
    {
        $this->__load();
        return parent::setUsuarioAudt($usuarioAudt);
    }

    public function getUsuarioAudt()
    {
        $this->__load();
        return parent::getUsuarioAudt();
    }

    public function setFechaAudt($fechaAudt)
    {
        $this->__load();
        return parent::setFechaAudt($fechaAudt);
    }

    public function getFechaAudt()
    {
        $this->__load();
        return parent::getFechaAudt();
    }

    public function setIpAudt($ipAudt)
    {
        $this->__load();
        return parent::setIpAudt($ipAudt);
    }

    public function getIpAudt()
    {
        $this->__load();
        return parent::getIpAudt();
    }

    public function setEstadoAudt($estadoAudt)
    {
        $this->__load();
        return parent::setEstadoAudt($estadoAudt);
    }

    public function getEstadoAudt()
    {
        $this->__load();
        return parent::getEstadoAudt();
    }

    public function setPkDatPostulante(\proyectos\hojaVidaBundle\Entity\DatosPostulante $pkDatPostulante = NULL)
    {
        $this->__load();
        return parent::setPkDatPostulante($pkDatPostulante);
    }

    public function getPkDatPostulante()
    {
        $this->__load();
        return parent::getPkDatPostulante();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pkInformacionPatCon', 'anoEje', 'ingresoAnualPublico', 'ingresoAnualPrivado', 'totalIngresoAnualPromedio', 'ahorrosSistema', 'ahorrosSinCustodia', 'nroPersonas', 'acreencias', 'ingresoAnualConyuge', 'usuarioAudt', 'fechaAudt', 'ipAudt', 'estadoAudt', 'pkDatPostulante');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}