<?php

namespace Proxies\__CG__\proyectos\hojaVidaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MaeDerecho extends \proyectos\hojaVidaBundle\Entity\MaeDerecho implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPkMaeDerecho()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["pkMaeDerecho"];
        }
        $this->__load();
        return parent::getPkMaeDerecho();
    }

    public function setUniversidad($universidad)
    {
        $this->__load();
        return parent::setUniversidad($universidad);
    }

    public function getUniversidad()
    {
        $this->__load();
        return parent::getUniversidad();
    }

    public function setNivel($nivel)
    {
        $this->__load();
        return parent::setNivel($nivel);
    }

    public function getNivel()
    {
        $this->__load();
        return parent::getNivel();
    }

    public function setMension($mension)
    {
        $this->__load();
        return parent::setMension($mension);
    }

    public function getMension()
    {
        $this->__load();
        return parent::getMension();
    }

    public function setAnio($anio)
    {
        $this->__load();
        return parent::setAnio($anio);
    }

    public function getAnio()
    {
        $this->__load();
        return parent::getAnio();
    }

    public function setUsuarioAudt($usuarioAudt)
    {
        $this->__load();
        return parent::setUsuarioAudt($usuarioAudt);
    }

    public function getUsuarioAudt()
    {
        $this->__load();
        return parent::getUsuarioAudt();
    }

    public function setFechaAudt($fechaAudt)
    {
        $this->__load();
        return parent::setFechaAudt($fechaAudt);
    }

    public function getFechaAudt()
    {
        $this->__load();
        return parent::getFechaAudt();
    }

    public function setIpAudt($ipAudt)
    {
        $this->__load();
        return parent::setIpAudt($ipAudt);
    }

    public function getIpAudt()
    {
        $this->__load();
        return parent::getIpAudt();
    }

    public function setEstadoAudt($estadoAudt)
    {
        $this->__load();
        return parent::setEstadoAudt($estadoAudt);
    }

    public function getEstadoAudt()
    {
        $this->__load();
        return parent::getEstadoAudt();
    }

    public function setPkDatAcademicos(\proyectos\hojaVidaBundle\Entity\DatosAcademicos $pkDatAcademicos = NULL)
    {
        $this->__load();
        return parent::setPkDatAcademicos($pkDatAcademicos);
    }

    public function getPkDatAcademicos()
    {
        $this->__load();
        return parent::getPkDatAcademicos();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pkMaeDerecho', 'universidad', 'nivel', 'mension', 'anio', 'usuarioAudt', 'fechaAudt', 'ipAudt', 'estadoAudt', 'pkDatAcademicos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}