<?php

namespace Proxies\__CG__\proyectos\curriculoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TdCurriculoItem extends \proyectos\curriculoBundle\Entity\TdCurriculoItem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdCurriculoItem()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idCurriculoItem"];
        }
        $this->__load();
        return parent::getIdCurriculoItem();
    }

    public function setFechaAuditoria($fechaAuditoria)
    {
        $this->__load();
        return parent::setFechaAuditoria($fechaAuditoria);
    }

    public function getFechaAuditoria()
    {
        $this->__load();
        return parent::getFechaAuditoria();
    }

    public function setExtension($extension)
    {
        $this->__load();
        return parent::setExtension($extension);
    }

    public function getExtension()
    {
        $this->__load();
        return parent::getExtension();
    }

    public function setFechaAnulacion($fechaAnulacion)
    {
        $this->__load();
        return parent::setFechaAnulacion($fechaAnulacion);
    }

    public function getFechaAnulacion()
    {
        $this->__load();
        return parent::getFechaAnulacion();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setEvaluacion1($evaluacion1)
    {
        $this->__load();
        return parent::setEvaluacion1($evaluacion1);
    }

    public function getEvaluacion1()
    {
        $this->__load();
        return parent::getEvaluacion1();
    }

    public function setEvaluacion2($evaluacion2)
    {
        $this->__load();
        return parent::setEvaluacion2($evaluacion2);
    }

    public function getEvaluacion2()
    {
        $this->__load();
        return parent::getEvaluacion2();
    }

    public function setConsensuado($consensuado)
    {
        $this->__load();
        return parent::setConsensuado($consensuado);
    }

    public function getConsensuado()
    {
        $this->__load();
        return parent::getConsensuado();
    }

    public function setFlagEval($flagEval)
    {
        $this->__load();
        return parent::setFlagEval($flagEval);
    }

    public function getFlagEval()
    {
        $this->__load();
        return parent::getFlagEval();
    }

    public function setFlagEval2($flagEval2)
    {
        $this->__load();
        return parent::setFlagEval2($flagEval2);
    }

    public function getFlagEval2()
    {
        $this->__load();
        return parent::getFlagEval2();
    }

    public function setEvaluado1($evaluado1)
    {
        $this->__load();
        return parent::setEvaluado1($evaluado1);
    }

    public function getEvaluado1()
    {
        $this->__load();
        return parent::getEvaluado1();
    }

    public function setEvaluado2($evaluado2)
    {
        $this->__load();
        return parent::setEvaluado2($evaluado2);
    }

    public function getEvaluado2()
    {
        $this->__load();
        return parent::getEvaluado2();
    }

    public function setFoja($foja)
    {
        $this->__load();
        return parent::setFoja($foja);
    }

    public function getFoja()
    {
        $this->__load();
        return parent::getFoja();
    }

    public function setObservacion($observacion)
    {
        $this->__load();
        return parent::setObservacion($observacion);
    }

    public function getObservacion()
    {
        $this->__load();
        return parent::getObservacion();
    }

    public function setNuevoItem($nuevoItem)
    {
        $this->__load();
        return parent::setNuevoItem($nuevoItem);
    }

    public function getNuevoItem()
    {
        $this->__load();
        return parent::getNuevoItem();
    }

    public function setPuntajeReporte($puntajeReporte)
    {
        $this->__load();
        return parent::setPuntajeReporte($puntajeReporte);
    }

    public function getPuntajeReporte()
    {
        $this->__load();
        return parent::getPuntajeReporte();
    }

    public function setEvaluadoAux($evaluadoAux)
    {
        $this->__load();
        return parent::setEvaluadoAux($evaluadoAux);
    }

    public function getEvaluadoAux()
    {
        $this->__load();
        return parent::getEvaluadoAux();
    }

    public function setFlagEvalAux($flagEvalAux)
    {
        $this->__load();
        return parent::setFlagEvalAux($flagEvalAux);
    }

    public function getFlagEvalAux()
    {
        $this->__load();
        return parent::getFlagEvalAux();
    }

    public function setPuntajeAux($puntajeAux)
    {
        $this->__load();
        return parent::setPuntajeAux($puntajeAux);
    }

    public function getPuntajeAux()
    {
        $this->__load();
        return parent::getPuntajeAux();
    }

    public function setFoja2($foja2)
    {
        $this->__load();
        return parent::setFoja2($foja2);
    }

    public function getFoja2()
    {
        $this->__load();
        return parent::getFoja2();
    }

    public function setObservacion2($observacion2)
    {
        $this->__load();
        return parent::setObservacion2($observacion2);
    }

    public function getObservacion2()
    {
        $this->__load();
        return parent::getObservacion2();
    }

    public function setIdCurriculo(\proyectos\curriculoBundle\Entity\TmCurriculo $idCurriculo = NULL)
    {
        $this->__load();
        return parent::setIdCurriculo($idCurriculo);
    }

    public function getIdCurriculo()
    {
        $this->__load();
        return parent::getIdCurriculo();
    }

    public function setIdItem(\proyectos\curriculoBundle\Entity\TmItem $idItem = NULL)
    {
        $this->__load();
        return parent::setIdItem($idItem);
    }

    public function getIdItem()
    {
        $this->__load();
        return parent::getIdItem();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idCurriculoItem', 'fechaAuditoria', 'extension', 'fechaAnulacion', 'estado', 'evaluacion1', 'evaluacion2', 'consensuado', 'flagEval', 'flagEval2', 'evaluado1', 'evaluado2', 'foja', 'observacion', 'nuevoItem', 'puntajeReporte', 'evaluadoAux', 'flagEvalAux', 'puntajeAux', 'foja2', 'observacion2', 'idCurriculo', 'idItem');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}