<?php

namespace Proxies\__CG__\proyectos\curriculoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class TmItem extends \proyectos\curriculoBundle\Entity\TmItem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdItem()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idItem"];
        }
        $this->__load();
        return parent::getIdItem();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setPuntaje($puntaje)
    {
        $this->__load();
        return parent::setPuntaje($puntaje);
    }

    public function getPuntaje()
    {
        $this->__load();
        return parent::getPuntaje();
    }

    public function setPuntajeMaximo($puntajeMaximo)
    {
        $this->__load();
        return parent::setPuntajeMaximo($puntajeMaximo);
    }

    public function getPuntajeMaximo()
    {
        $this->__load();
        return parent::getPuntajeMaximo();
    }

    public function setFormato($formato)
    {
        $this->__load();
        return parent::setFormato($formato);
    }

    public function getFormato()
    {
        $this->__load();
        return parent::getFormato();
    }

    public function setFlag($flag)
    {
        $this->__load();
        return parent::setFlag($flag);
    }

    public function getFlag()
    {
        $this->__load();
        return parent::getFlag();
    }

    public function setFlagUpload($flagUpload)
    {
        $this->__load();
        return parent::setFlagUpload($flagUpload);
    }

    public function getFlagUpload()
    {
        $this->__load();
        return parent::getFlagUpload();
    }

    public function setFff($fff)
    {
        $this->__load();
        return parent::setFff($fff);
    }

    public function getFff()
    {
        $this->__load();
        return parent::getFff();
    }

    public function setMuestraReporte($muestraReporte)
    {
        $this->__load();
        return parent::setMuestraReporte($muestraReporte);
    }

    public function getMuestraReporte()
    {
        $this->__load();
        return parent::getMuestraReporte();
    }

    public function setFlagCalculofecha($flagCalculofecha)
    {
        $this->__load();
        return parent::setFlagCalculofecha($flagCalculofecha);
    }

    public function getFlagCalculofecha()
    {
        $this->__load();
        return parent::getFlagCalculofecha();
    }

    public function addIdCampo(\proyectos\curriculoBundle\Entity\TdCampos $idCampo)
    {
        $this->__load();
        return parent::addIdCampo($idCampo);
    }

    public function removeIdCampo(\proyectos\curriculoBundle\Entity\TdCampos $idCampo)
    {
        $this->__load();
        return parent::removeIdCampo($idCampo);
    }

    public function getIdCampo()
    {
        $this->__load();
        return parent::getIdCampo();
    }

    public function setIdItemPadre(\proyectos\curriculoBundle\Entity\TmItem $idItemPadre = NULL)
    {
        $this->__load();
        return parent::setIdItemPadre($idItemPadre);
    }

    public function getIdItemPadre()
    {
        $this->__load();
        return parent::getIdItemPadre();
    }

    public function setIdTipoCargo(\proyectos\curriculoBundle\Entity\TrTipoCargo $idTipoCargo = NULL)
    {
        $this->__load();
        return parent::setIdTipoCargo($idTipoCargo);
    }

    public function getIdTipoCargo()
    {
        $this->__load();
        return parent::getIdTipoCargo();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idItem', 'descripcion', 'puntaje', 'puntajeMaximo', 'formato', 'flag', 'flagUpload', 'fff', 'muestraReporte', 'flagCalculofecha', 'idCampo', 'idItemPadre', 'idTipoCargo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}