<?php

namespace Proxies\__CG__\proyectos\hojaVidaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DocDesProfesional extends \proyectos\hojaVidaBundle\Entity\DocDesProfesional implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPkExpProfesional()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["pkExpProfesional"];
        }
        $this->__load();
        return parent::getPkExpProfesional();
    }

    public function setNumExp($numExp)
    {
        $this->__load();
        return parent::setNumExp($numExp);
    }

    public function getNumExp()
    {
        $this->__load();
        return parent::getNumExp();
    }

    public function setDdas($ddas)
    {
        $this->__load();
        return parent::setDdas($ddas);
    }

    public function getDdas()
    {
        $this->__load();
        return parent::getDdas();
    }

    public function setDdae($ddae)
    {
        $this->__load();
        return parent::setDdae($ddae);
    }

    public function getDdae()
    {
        $this->__load();
        return parent::getDdae();
    }

    public function setMateria($materia)
    {
        $this->__load();
        return parent::setMateria($materia);
    }

    public function getMateria()
    {
        $this->__load();
        return parent::getMateria();
    }

    public function setEspecialidad($especialidad)
    {
        $this->__load();
        return parent::setEspecialidad($especialidad);
    }

    public function getEspecialidad()
    {
        $this->__load();
        return parent::getEspecialidad();
    }

    public function setCalificacion1($calificacion1)
    {
        $this->__load();
        return parent::setCalificacion1($calificacion1);
    }

    public function getCalificacion1()
    {
        $this->__load();
        return parent::getCalificacion1();
    }

    public function setCalificacion2($calificacion2)
    {
        $this->__load();
        return parent::setCalificacion2($calificacion2);
    }

    public function getCalificacion2()
    {
        $this->__load();
        return parent::getCalificacion2();
    }

    public function setUsuarioAudt($usuarioAudt)
    {
        $this->__load();
        return parent::setUsuarioAudt($usuarioAudt);
    }

    public function getUsuarioAudt()
    {
        $this->__load();
        return parent::getUsuarioAudt();
    }

    public function setFechaAudt($fechaAudt)
    {
        $this->__load();
        return parent::setFechaAudt($fechaAudt);
    }

    public function getFechaAudt()
    {
        $this->__load();
        return parent::getFechaAudt();
    }

    public function setIpAudt($ipAudt)
    {
        $this->__load();
        return parent::setIpAudt($ipAudt);
    }

    public function getIpAudt()
    {
        $this->__load();
        return parent::getIpAudt();
    }

    public function setEstadoAudt($estadoAudt)
    {
        $this->__load();
        return parent::setEstadoAudt($estadoAudt);
    }

    public function getEstadoAudt()
    {
        $this->__load();
        return parent::getEstadoAudt();
    }

    public function setPkDatPostulante(\proyectos\hojaVidaBundle\Entity\DatosPostulante $pkDatPostulante = NULL)
    {
        $this->__load();
        return parent::setPkDatPostulante($pkDatPostulante);
    }

    public function getPkDatPostulante()
    {
        $this->__load();
        return parent::getPkDatPostulante();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pkExpProfesional', 'numExp', 'ddas', 'ddae', 'materia', 'especialidad', 'calificacion1', 'calificacion2', 'usuarioAudt', 'fechaAudt', 'ipAudt', 'estadoAudt', 'pkDatPostulante');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}