curriculo:
    resource: "@curriculoBundle/Controller/"
    type:     annotation
    prefix:   /curriculow

hoja_vida:
    resource: "@hojaVidaBundle/Controller/"
    type:     annotation
    prefix:   /


