acceso:
    resource: "@AccesoBundle/Controller/"
    type:     annotation
    prefix:   /

curriculo:
    resource: "@curriculoBundle/Controller/"
    type:     annotation
    prefix:   /curriculo

hoja_vida:
    resource: "@hojaVidaBundle/Controller/"
    type:     annotation
    prefix:   /registro


