security:
        encoders:
           proyectos\curriculoBundle\Entity\SUsuario: 
                                              algorithm:        md5
                                              iterations:       0
                                              encode_as_base64: false 
        firewalls:
            frontend:
                  pattern: ^/*
                  anonymous: ~
                  form_login:
                        login_path: _login
                        check_path: _login_check
                        default_target_path: _lista_usuarios
                        use_forward: false
                  logout:
                        path: _logout
                        target: _login    
                        
        access_control:
               - { path: ^/curriculo/*, roles: ROLE_USUARIO }
               - { path: ^/registro/*, roles: ROLE_USUARIO }

        providers:
            usuarios:
                 entity: { class: proyectos\curriculoBundle\Entity\SUsuario, property: dni }