security:
        encoders:
           proyectos\curriculoBundle\Entity\SUsuario: 
                                              algorithm:        md5
                                              iterations:       0
                                              encode_as_base64: false 
        firewalls:
            frontend:
                  pattern: ^/*
                  anonymous: ~
                  form_login:
                        login_path: _login
                        check_path: _login_check
                        default_target_path: _panel_usuario
                  logout:
                        path: _logout
                        target: _login    
        access_control:
#               - { path: ^/curriculo/*, roles: ROLE_USUARIO }
#               - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        providers:
            usuarios:
                 entity: { class: proyectos\curriculoBundle\Entity\SUsuario, property: dni }