CalJudFis:
    type: entity
    table: cal_jud_fis
    fields:
        pkExpJudFis:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: PK_EXP_JUD_FIS
            generator:
                strategy: IDENTITY
        numExp:
            type: integer
            unsigned: false
            nullable: true
            column: NUM_EXP
        tipResolucion:
            type: string
            length: 30
            fixed: false
            nullable: true
            column: TIP_RESOLUCION
        fechaRes:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: FECHA_RES
        ddagraviado:
            type: string
            length: 30
            fixed: false
            nullable: true
            column: DDAGRAVIADO
        ddagresor:
            type: string
            length: 30
            fixed: false
            nullable: true
            column: DDAGRESOR
        materia:
            type: string
            length: 30
            fixed: false
            nullable: true
            column: MATERIA
        especialidad:
            type: string
            length: 30
            fixed: false
            nullable: true
            column: ESPECIALIDAD
        nota:
            type: float
            nullable: true
            column: NOTA
        pkExpProfesional:
            type: integer
            unsigned: false
            nullable: true
            column: PK_EXP_PROFESIONAL
        usuarioAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: USUARIO_AUDT
        fechaAudt:
            type: datetime
            nullable: true
            column: FECHA_AUDT
        ipAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: IP_AUDT
        estadoAudt:
            type: integer
            unsigned: false
            nullable: true
            column: ESTADO_AUDT
    manyToOne:
        pkDatPostulante:
            targetEntity: DatosPostulante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PK_DAT_POSTULANTE:
                    referencedColumnName: PK_DAT_POSTULANTE
            orphanRemoval: false
    lifecycleCallbacks: {  }
