DatosPostulante:
    type: entity
    table: datos_postulante
    fields:
        pkDatPostulante:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: PK_DAT_POSTULANTE
            generator:
                strategy: IDENTITY
        pkSusuario:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: PK_SUSUARIO
        cargoAPostular:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: CARGO_A_POSTULAR
        condicion:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: CONDICION
        tipoCurso:
            type: string
            length: 8
            fixed: false
            nullable: true
            column: TIPO_CURSO
        nota:
            type: float
            nullable: true
            column: NOTA
        prePromedio:
            type: float
            nullable: true
            column: PRE_PROMEDIO
        ordenMerito:
            type: integer
            unsigned: false
            nullable: true
            column: ORDEN_MERITO
        plazasVacantes:
            type: integer
            unsigned: false
            nullable: true
            column: PLAZAS_VACANTES
        examenConocimientos:
            type: string
            length: 80
            fixed: false
            nullable: false
            column: EXAMEN_CONOCIMIENTOS
        afiliacionCurricular:
            type: string
            length: 80
            fixed: false
            nullable: false
            column: AFILIACION_CURRICULAR
        usuarioAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: USUARIO_AUDT
        fechaAudt:
            type: datetime
            nullable: true
            column: FECHA_AUDT
        ipAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: IP_AUDT
        estadoAudt:
            type: integer
            unsigned: false
            nullable: true
            column: ESTADO_AUDT
    lifecycleCallbacks: {  }
