DatosPersonales:
    type: entity
    table: datos_personales
    fields:
        idDatPersonal:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID_DAT_PERSONAL
            generator:
                strategy: IDENTITY
        nombres:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: NOMBRES
        apellidos:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: APELLIDOS
        lugarNac:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: LUGAR_NAC
        fechaNac:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: FECHA_NAC
        edad:
            type: integer
            unsigned: false
            nullable: true
            column: EDAD
        dni:
            type: string
            length: 12
            fixed: false
            nullable: true
            column: DNI
        discapacidad:
            type: string
            length: 2
            fixed: false
            nullable: true
            column: DISCAPACIDAD
        certDiscapacidad:
            type: string
            length: 300
            fixed: false
            nullable: true
            column: CERT_DISCAPACIDAD
        foto:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: FOTO
        usuarioAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: USUARIO_AUDT
        fechaAudt:
            type: datetime
            nullable: true
            column: FECHA_AUDT
        ipAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: IP_AUDT
    lifecycleCallbacks: {  }
