InfoIngresosConyuge:
    type: entity
    table: info_ingresos_conyuge
    fields:
        pkPatConyuge:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: PK_PAT_CONYUGE
            generator:
                strategy: IDENTITY
        anoEje:
            type: integer
            unsigned: false
            nullable: true
            column: ANO_EJE
        nombre:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: NOMBRE
        ingresoMensualPromedio:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: INGRESO_MENSUAL_PROMEDIO
        dependencia:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: DEPENDENCIA
        cargo:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: CARGO
        usuarioAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: USUARIO_AUDT
        fechaAudt:
            type: datetime
            nullable: true
            column: FECHA_AUDT
        ipAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: IP_AUDT
        estadoAudt:
            type: integer
            unsigned: false
            nullable: true
            column: ESTADO_AUDT
    manyToOne:
        pkDatPostulante:
            targetEntity: DatosPostulante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PK_DAT_POSTULANTE:
                    referencedColumnName: PK_DAT_POSTULANTE
            orphanRemoval: false
    lifecycleCallbacks: {  }
