InformacionPatrimonialConyuge:
    type: entity
    table: informacion_patrimonial_conyuge
    fields:
        pkInformacionPatCon:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: PK_INFORMACION_PAT_CON
            generator:
                strategy: IDENTITY
        anoEje:
            type: integer
            unsigned: false
            nullable: true
            column: ANO_EJE
        ingresoAnualPublico:
            type: float
            nullable: true
            column: INGRESO_ANUAL_PUBLICO
        ingresoAnualPrivado:
            type: float
            nullable: true
            column: INGRESO_ANUAL_PRIVADO
        totalIngresoAnualPromedio:
            type: float
            nullable: true
            column: TOTAL_INGRESO_ANUAL_PROMEDIO
        ahorrosSistema:
            type: float
            nullable: true
            column: AHORROS_SISTEMA
        ahorrosSinCustodia:
            type: float
            nullable: true
            column: AHORROS_SIN_CUSTODIA
        nroPersonas:
            type: float
            nullable: true
            column: NRO_PERSONAS
        acreencias:
            type: float
            nullable: true
            column: ACREENCIAS
        ingresoAnualConyuge:
            type: float
            nullable: true
            column: INGRESO_ANUAL_CONYUGE
    manyToOne:
        pkDatPostulante:
            targetEntity: DatosPostulante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PK_DAT_POSTULANTE:
                    referencedColumnName: PK_DAT_POSTULANTE
            orphanRemoval: false
    lifecycleCallbacks: {  }
