InformacionOficinas:
    type: entity
    table: informacion_oficinas
    fields:
        pkProcesosInformacionOficinas:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: PK_PROCESOS_INFORMACION_OFICINAS
            generator:
                strategy: IDENTITY
        idOficina:
            type: integer
            unsigned: false
            nullable: true
            column: ID_OFICINA
        descripcion:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: DESCRIPCION
    manyToOne:
        pkDatPostulante:
            targetEntity: DatosPostulante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PK_DAT_POSTULANTE:
                    referencedColumnName: PK_DAT_POSTULANTE
            orphanRemoval: false
    lifecycleCallbacks: {  }
