Ingresos:
    type: entity
    table: ingresos
    fields:
        pkIngresos:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: PK_INGRESOS
            generator:
                strategy: IDENTITY
        anoEje:
            type: float
            nullable: true
            column: ANO_EJE
        valor:
            type: float
            nullable: true
            column: VALOR
        usuarioAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: USUARIO_AUDT
        fechaAudt:
            type: datetime
            nullable: true
            column: FECHA_AUDT
        ipAudt:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: IP_AUDT
        descripcion:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: DESCRIPCION
    manyToOne:
        pkDatPostulante:
            targetEntity: DatosPostulante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PK_DAT_POSTULANTE:
                    referencedColumnName: PK_DAT_POSTULANTE
            orphanRemoval: false
    lifecycleCallbacks: {  }
