LicenciasOtorgadas:
    type: entity
    table: licencias_otorgadas
    fields:
        pkLicenciasOtor:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: PK_LICENCIAS_OTOR
            generator:
                strategy: IDENTITY
        anio:
            type: string
            length: 4
            fixed: false
            nullable: true
            column: ANIO
        motivo:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: MOTIVO
        dias:
            type: integer
            unsigned: false
            nullable: true
            column: DIAS
    manyToOne:
        pkDatPostulante:
            targetEntity: DatosPostulante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PK_DAT_POSTULANTE:
                    referencedColumnName: PK_DAT_POSTULANTE
            orphanRemoval: false
    lifecycleCallbacks: {  }
