MeritosUniv:
    type: entity
    table: meritos_univ
    fields:
        pkMeritosUnivDet:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: PK_MERITOS_UNIV_DET
            generator:
                strategy: IDENTITY
        puesto:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: PUESTO
        universidad:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: UNIVERSIDAD
        anio:
            type: string
            length: 4
            fixed: false
            nullable: true
            column: ANIO
    manyToOne:
        pkDatAcademicos:
            targetEntity: DatosAcademicos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PK_DAT_ACADEMICOS:
                    referencedColumnName: PK_DAT_ACADEMICOS
            orphanRemoval: false
    lifecycleCallbacks: {  }
