OtrosIngresos:
    type: entity
    table: otros_ingresos
    fields:
        pkIngresosOtros:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: PK_INGRESOS_OTROS
            generator:
                strategy: IDENTITY
        descripcion:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: DESCRIPCION
        monto:
            type: float
            nullable: true
            column: MONTO
    manyToOne:
        pkDatPostulante:
            targetEntity: DatosPostulante
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                PK_DAT_POSTULANTE:
                    referencedColumnName: PK_DAT_POSTULANTE
            orphanRemoval: false
    lifecycleCallbacks: {  }
