TdCurriculoEvaluacion:
    type: entity
    table: td_curriculo_evaluacion
    fields:
        idEvaluacion:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_evaluacion
        usuario:
            type: string
            length: 50
            fixed: false
            nullable: false
        inicioEvaluacion:
            type: datetime
            nullable: true
            column: inicio_evaluacion
        finEvaluacion:
            type: datetime
            nullable: true
            column: fin_evaluacion
    oneToOne:
        idCurriculo:
            targetEntity: TmCurriculo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_curriculo:
                    referencedColumnName: id_curriculo
            orphanRemoval: false
    lifecycleCallbacks: {  }
