TdCurriculoItem:
    type: entity
    table: td_curriculo_item
    fields:
        idCurriculoItem:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_curriculo_item
            generator:
                strategy: IDENTITY
        fechaAuditoria:
            type: datetime
            nullable: true
            column: fecha_auditoria
        extension:
            type: string
            length: 10
            fixed: false
            nullable: true
        fechaAnulacion:
            type: datetime
            nullable: true
            column: fecha_anulacion
        estado:
            type: string
            length: 1
            fixed: true
            nullable: true
        evaluacion1:
            type: decimal
            nullable: false
        evaluacion2:
            type: decimal
            nullable: false
        consensuado:
            type: decimal
            nullable: false
        flagEval:
            type: integer
            unsigned: false
            nullable: false
            column: flag_eval
        flagEval2:
            type: integer
            unsigned: false
            nullable: false
            column: flag_eval2
        evaluado1:
            type: integer
            unsigned: false
            nullable: false
        evaluado2:
            type: integer
            unsigned: false
            nullable: false
        foja:
            type: string
            length: 50
            fixed: false
            nullable: true
        observacion:
            type: string
            length: 500
            fixed: false
            nullable: true
        nuevoItem:
            type: integer
            unsigned: false
            nullable: true
            column: nuevo_item
        puntajeReporte:
            type: decimal
            nullable: true
            column: puntaje_reporte
        evaluadoAux:
            type: integer
            unsigned: false
            nullable: false
            column: evaluado_aux
        flagEvalAux:
            type: integer
            unsigned: false
            nullable: false
            column: flag_eval_aux
        puntajeAux:
            type: decimal
            nullable: false
            column: puntaje_aux
        foja2:
            type: string
            length: 50
            fixed: false
            nullable: true
        observacion2:
            type: string
            length: 255
            fixed: false
            nullable: true
    manyToOne:
        idCurriculo:
            targetEntity: TmCurriculo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_curriculo:
                    referencedColumnName: id_curriculo
            orphanRemoval: false
        idItem:
            targetEntity: TmItem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_item:
                    referencedColumnName: id_item
            orphanRemoval: false
    lifecycleCallbacks: {  }
