TmConvocatoria:
    type: entity
    table: tm_convocatoria
    fields:
        idConvocatoria:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_convocatoria
            generator:
                strategy: IDENTITY
        descripcion:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
