TrPlaza:
    type: entity
    table: tr_plaza
    fields:
        idPlaza:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_plaza
            generator:
                strategy: IDENTITY
        descripcion:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
